"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class node_out_t(object):
    __slots__ = ["node_name", "nav_long", "nav_lat", "nav_depth", "node_report_local", "appcast"]

    def __init__(self):
        self.node_name = ""
        self.nav_long = 0.0
        self.nav_lat = 0.0
        self.nav_depth = 0.0
        self.node_report_local = ""
        self.appcast = ""

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(node_out_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __node_name_encoded = self.node_name.encode('utf-8')
        buf.write(struct.pack('>I', len(__node_name_encoded)+1))
        buf.write(__node_name_encoded)
        buf.write("\0")
        buf.write(struct.pack(">ddd", self.nav_long, self.nav_lat, self.nav_depth))
        __node_report_local_encoded = self.node_report_local.encode('utf-8')
        buf.write(struct.pack('>I', len(__node_report_local_encoded)+1))
        buf.write(__node_report_local_encoded)
        buf.write("\0")
        __appcast_encoded = self.appcast.encode('utf-8')
        buf.write(struct.pack('>I', len(__appcast_encoded)+1))
        buf.write(__appcast_encoded)
        buf.write("\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != node_out_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return node_out_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = node_out_t()
        __node_name_len = struct.unpack('>I', buf.read(4))[0]
        self.node_name = buf.read(__node_name_len)[:-1].decode('utf-8', 'replace')
        self.nav_long, self.nav_lat, self.nav_depth = struct.unpack(">ddd", buf.read(24))
        __node_report_local_len = struct.unpack('>I', buf.read(4))[0]
        self.node_report_local = buf.read(__node_report_local_len)[:-1].decode('utf-8', 'replace')
        __appcast_len = struct.unpack('>I', buf.read(4))[0]
        self.appcast = buf.read(__appcast_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if node_out_t in parents: return 0
        tmphash = (0x7903f40f10865447) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if node_out_t._packed_fingerprint is None:
            node_out_t._packed_fingerprint = struct.pack(">Q", node_out_t._get_hash_recursive([]))
        return node_out_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

